**Exercise 1: Create a Jupyter Notebook**

Create a new Jupyter notebook called ```DataScienceEcosystem.ipynb```

___

**Exercise 2: Create markdown cell with title of the notebook**

Create a markdown cell with the title ```Data Science Tools and Ecosystem``` using H1 style heading.

# Data Science Tools and Ecosystem

___

**Exercise 3 - Create a markdown cell for an introduction**

In this notebook, Data Science Tools and Ecosystem are summarized. Like programming languages, libraries, tools, and others

**Objectives:**

- Popular languages for Data Science
- Popular libraries for Data Science
- The 3 most used tools for data science
- Some examples of evaluating arithmetic expressions in Python

___

**Exercise 4 - Create a markdown cell to list data science languages**

Some of the popular languages that Data Scientists use are:

1. Python
2. R
3. Julia
4. Scala
5. Java
6. SQL

___

**Exercise 5 - Create a markdown cell to list data science libraries**

Some of the commonly used libraries used by Data Scientists include:

1. NumPy
2. Pandas
3. Matplotlib
4. Seaborn
5. Scikit-learn
6. Keras
7. TensorFlow
8. Pytorch
9. BigDL
10. Vegas
11. ggplot
12. Ploty

___

**Exercise 6 - Create a markdown cell with a table of Data Science tools**

| Data Science Tools |
---------------------
| Jupyter Notebook |
| R Studio |
| Apache Spark |

___

**Exercise 7 - Create a markdown cell introducing arithmetic expression examples**

### Below are a few examples of evaluating arithmetic expressions in Python.

___

**Exercise 8 - Create a code cell to multiply and add numbers**

In [1]:
# This a simple arithmetic expression to mutiply then add integers
(3*4)+5

17

___

**Exercise 9 - Create a code cell to convert minutes to hours**

In [2]:
# This will convert 200 minutes to hours by diving by 60
200/60

3.3333333333333335

___

**Exercise 10 - Insert a markdown cell to list Objectives**

Below the introduction cell created in Exercise 3, insert a new markdown cell to list the objectives that this notebook covered (i.e. some of the key takeaways from the course). In this new cell start with an introductory line titled: ```Objectives:``` in bold font. Then using an ```unordered``` list (bullets) indicate 3 to 5 items covered in this notebook, such as ```List popular languages for Data Science```.

___

**Exercise 11 - Create a markdown cell to indicate the Author's name**

## Author: Shamsiddin

___